=== isabella232/addonfactory-cloudconnect-library/package/bin/schema/hcm_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "hcm_json_schema_builder._Checkpoint": {
      "type": "object",
      "properties": {
        "save": {
          "type": "boolean",
          "default": true
        },
        "namespace": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "content": {
          "type": "object"
        }
      },
      "required": [
        "content"
      ],
      "additionalProperties": true
    },
    "hcm_json_schema_builder._FileOutput": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object",
          "properties": {
            "source_key": {
              "type": "string"
            },
            "format": {
              "type": "string",
              "enum": [
                "splunk_xml",
                "raw"
              ]
            }
          },
          "required": [
            "source_key",
            "format"
          ],
          "additionalProperties": true
        },
        "type": {
          "type": "string",
          "enum": [
            "file"
          ]
        },
        "options": {
          "type": "object"
        }
      },
      "required": [
        "data",
        "options"
      ],
      "additionalProperties": true
    },
    "hcm_json_schema_builder._Proxy": {
      "type": "object",
      "properties": {
        "enabled": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "string"
            }
          ]
        },
        "host": {
          "type": "string"
        },
        "port": {
          "oneOf": [
            {
              "type": "integer"
            },
            {
              "type": "string"
            }
          ]
        },
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "rdns": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "enabled",
        "host",
        "port"
      ],
      "additionalProperties": true
    },
    "hcm_json_schema_builder._Request": {
      "type": "object",
      "properties": {
        "context": {
          "type": "object"
        },
        "auth": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "digest",
                "basic64"
              ]
            },
            "options": {
              "type": "object"
            }
          },
          "required": [
            "type"
          ],
          "additionalProperties": true
        },
        "headers": {
          "type": "object"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "method": {
          "type": "string",
          "enum": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "PATCH"
          ]
        },
        "stop_condition": {
          "type": "string",
          "enum": [
            "empty",
            "once"
          ],
          "default": "empty"
        },
        "output": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/hcm_json_schema_builder._StdoutOutput"
              },
              {
                "$ref": "#/definitions/hcm_json_schema_builder._FileOutput"
              }
            ]
          },
          "minItems": 1
        },
        "params": {
          "type": "object"
        },
        "checkpoint": {
          "$ref": "#/definitions/hcm_json_schema_builder._Checkpoint"
        }
      },
      "required": [
        "context",
        "headers",
        "url",
        "method",
        "stop_condition",
        "params"
      ],
      "additionalProperties": true
    },
    "hcm_json_schema_builder._StdoutOutput": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object",
          "properties": {
            "source_key": {
              "type": "string"
            },
            "format": {
              "type": "string",
              "enum": [
                "splunk_xml",
                "raw"
              ]
            }
          },
          "required": [
            "source_key",
            "format"
          ],
          "additionalProperties": true
        },
        "type": {
          "type": "string",
          "enum": [
            "stdout"
          ]
        },
        "options": {
          "type": "object",
          "properties": {
            "index": {
              "type": "string"
            },
            "host": {
              "type": "string"
            },
            "sourcetype": {
              "type": "string"
            },
            "source": {
              "type": "string"
            }
          },
          "required": [
            "index",
            "host",
            "sourcetype",
            "source"
          ]
        }
      },
      "required": [
        "data",
        "type",
        "options"
      ],
      "additionalProperties": true
    }
  },
  "type": "object",
  "properties": {
    "__version__": {
      "type": "string",
      "pattern": "[\\d\\.]+"
    },
    "parameters": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "proxy": {
      "$ref": "#/definitions/hcm_json_schema_builder._Proxy"
    },
    "hec": {
      "type": "object"
    },
    "logging": {
      "type": "object"
    },
    "requests": {
      "type": "array",
      "items": [
        {
          "$ref": "#/definitions/hcm_json_schema_builder._Request"
        }
      ],
      "minItems": 1
    }
  },
  "required": [
    "__version__",
    "parameters",
    "hec",
    "logging",
    "requests"
  ],
  "additionalProperties": false
}

=== isabella232/addonfactory-cloudconnect-library/test/unit/data/hcm_1.json
{
  "__version__": "1.0.0",
  "parameters": [
    "name",
    "url",
    "sysparm_limit",
    "table_name",
    "api_key",
    "since_when",
    "host",
    "index",
    "sourcetype",
    "source",
    "checkpoint_dir",
    "collection_interval",
    "proxy_enable",
    "proxy_host",
    "proxy_type",
    "proxy_username",
    "hec_host",
    "hec_port",
    "logging_level"
  ],
  "proxy": {
    "enabled": "$proxy_enable$",
    "host": "$proxy_host$",
    "port": "$proxy_port$",
    "username": "$proxy_username$",
    "passowrd": "$proxy_password$",
    "rdns": "$proxy_rdns$",
    "type": "$proxy_type$"
  },
  "hec": {
    "host": "$hec_host$",
    "port": "$hec_port$"
  },
  "logging": {
    "level": "$logging_level$"
  },
  "requests": [
    {
      "context": {
        "since_when": {
          "source_key": "$__response__$.body",
          "jsonpath": "$.result[(@.length-1)].sys_updated_on"
        }
      },
      "auth": {
        "type": "basic64",
        "options": {
        }
      },
      "url": "https://$url$/api/now/table/$table_name$",
      "headers": {
        "accept": "application/json",
        "auth": "$api_key$"
      },
      "method": "GET",
      "stop_condition": "empty",
      "output": [
        {
          "data": {
            "source_key": "$__response__$.body",
            "jsonpath": "$.result.*",
            "format": "splunk_xml"
          },
          "type": "stdout",
          "options": {
            "index": "$index$",
            "host": "$host$",
            "sourcetype": "$sourcetype$",
            "source": "$source$"
          }
        }
      ],
      "params": {
        "sysparm_limit": "$sysparm_limit$",
        "sysparm_query": "sys_updated_on>=$since_when$^ORDERBYsys_updated_on"
      },
      "checkpoint": {
        "save": true,
        "namespace": [
          "$name$",
          "$table_name$"
        ],
        "content": {
          "since_when": "$since_when$"
        }
      }
    }
  ]
}
